### ISSUE TITLE
can't see expected output after running with discordSdk

### ISSUE THREAD

**Issue by sheicraus** [Fraulk/gvp-activity#1]
hello, i need your help to show the expected content in discord activity 🙏

# What I did so far
* setup activity (following discord tutorial)
* locally run both `client` and `server`
<img width="1281" alt="Screenshot 2024-04-18 at 12 04 19 AM" src="https://github.com/Fraulk/gvp-activity/assets/68653710/ca9282fd-bdf5-49e8-ae82-260e7de89279">

# Issue
however, there's no content displayed in discord when tried running the activity
* note: i used `ngrok` for URL mapping
<img width="1710" alt="Screenshot 2024-04-18 at 12 10 31 AM" src="https://github.com/Fraulk/gvp-activity/assets/68653710/b7c3911c-1f1e-4c39-bf0e-8cd76f839397">

also got this error when running `client` locally in 3001 port:
<img width="837" alt="Screenshot 2024-04-18 at 12 06 16 AM" src="https://github.com/Fraulk/gvp-activity/assets/68653710/1c7cb0de-6b7a-4375-9e9b-5844d6d5c128">

any help is appreciated! thank you 🙏

**Comment by Fraulk** [comment]
hmm not sure if that's the solution but i remember having issue launching the project because of a problem with vite, and updating it to a version superior to 3.0.0 resolved it
if it's not that, did you correctly mapped all the url ? especially if you loads stuff externally, you need to add it to the list of url mapping in the dev portal
since i'm using cloudfared i didn't had any issue there, and so i'm using the npm scripts in the project root

**Comment by sheicraus** [comment]
@Fraulk thank you! i tried using cloudfared and it worked! but the content seems stuck at "Loading"
or do i need to wait for a few mins? 

<img width="1710" alt="Screenshot 2024-04-18 at 10 21 21 PM" src="https://github.com/Fraulk/gvp-activity/assets/68653710/c3b435e3-d364-4bb5-9d83-aba57bb5622f">

**Comment by Fraulk** [comment]
@sheicraus the loading shouldn't take long, check in the server or client console what's the error (you can open discord's console with `Ctrl + Shift + I`)
